INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (1,'estrella','Vandeplas',1,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (2,'tameka','Garcia',47,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (3,'diggory','Bert',8,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (4,'bethuel','Franssens',17,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (5,'laurie','Bonny',10,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (6,'barbora','Koopmans',13,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (7,'jaqueline','Holemans',31,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (8,'irinei','Drappier',46,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (9,'jacinta','Spruyt',16,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (10,'abbey','Darcis',44,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (11,'frankie','Counet',25,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (12,'Swan','Charles',46,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (13,'zora','Vos',6,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (14,'cari','Dossin',21,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (15,'serhat','Dartevelle',12,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (16,'yitzhak','Goubert',37,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (17,'jaqueline','Braham',1,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (18,'lark','Deloose',24,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (19,'molly','Blancquaert',25,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (20,'ettie','Vanleeuw',42,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (21,'Elias','Vanbilsen',44,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (22,'isleen','Mommen',18,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (23,'tzofiya','Gilot',11,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (24,'Lylou','Hassani',47,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (25,'holden','Melnyk',34,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (26,'orly','Belkadi',37,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (27,'ruairidh','Beeckmans',10,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (28,'Nawal','Pirenne',42,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (29,'zisel','Dejean',41,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (30,'fariha','Carrette',14,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (31,'mareike','Mouchart',23,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (32,'Charlie','Aydemir',32,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (33,'harmon','Baeten',9,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (34,'mellan','Emmers',19,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (35,'aphrodisios','Mkrtchyan',25,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (36,'jeroen','Baise',13,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (37,'Hatouma','Gommeren',28,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (38,'melchor','Capoen',17,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (39,'ashtoreth','Vanhoecke',41,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (40,'surendra','Jooris',45,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (41,'poppy','Rodriguez',43,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (42,'filep','Bogers',36,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (43,'woodrow','Dezitter',30,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (44,'howard','Mans',50,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (45,'phyllis','Leplae',8,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (46,'melicent','Broothaers',10,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (47,'Sandra','Oorts',43,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (48,'casimiro','Sacco',37,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (49,'ignazio','Dumon',50,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Employees (employee_id,first_name,last_name,department_id,hire_date) VALUES (50,'christiaan','Kesteloot',37,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Departments (department_id,department_name) VALUES (1,'Engelbr�cke');
INSERT INTO Departments (department_id,department_name) VALUES (2,'Rue de la Poste');
INSERT INTO Departments (department_id,department_name) VALUES (3,'Rue de la Sarthe');
INSERT INTO Departments (department_id,department_name) VALUES (4,'Avenue de l'Or�e');
INSERT INTO Departments (department_id,department_name) VALUES (5,'Rue de la Briqueterie');
INSERT INTO Departments (department_id,department_name) VALUES (6,'Chemin Saint-Landry');
INSERT INTO Departments (department_id,department_name) VALUES (7,'Rue du Paradis');
INSERT INTO Departments (department_id,department_name) VALUES (8,'Chemin de Lecelles');
INSERT INTO Departments (department_id,department_name) VALUES (9,'Zur Eidt');
INSERT INTO Departments (department_id,department_name) VALUES (10,'Rue du Casino');
INSERT INTO Departments (department_id,department_name) VALUES (11,'Morsheck');
INSERT INTO Departments (department_id,department_name) VALUES (12,'Rue Isi Collin');
INSERT INTO Departments (department_id,department_name) VALUES (13,'Rond Bois');
INSERT INTO Departments (department_id,department_name) VALUES (14,'Val de la Berwinne');
INSERT INTO Departments (department_id,department_name) VALUES (15,'Rue Olivier Benne');
INSERT INTO Departments (department_id,department_name) VALUES (16,'Ruelle Boulvin');
INSERT INTO Departments (department_id,department_name) VALUES (17,'Rue du Docteur Haquin');
INSERT INTO Departments (department_id,department_name) VALUES (18,'Rue Trou-du-Renard');
INSERT INTO Departments (department_id,department_name) VALUES (19,'Cit� Roland');
INSERT INTO Departments (department_id,department_name) VALUES (20,'Rue de la Papeterie');
INSERT INTO Departments (department_id,department_name) VALUES (21,'Chemin de Ramillies');
INSERT INTO Departments (department_id,department_name) VALUES (22,'rue du Perron');
INSERT INTO Departments (department_id,department_name) VALUES (23,'Rue du Br�ll');
INSERT INTO Departments (department_id,department_name) VALUES (24,'Ch�teau Barbier');
INSERT INTO Departments (department_id,department_name) VALUES (25,'W� G�rard');
INSERT INTO Departments (department_id,department_name) VALUES (26,'Place Desoil');
INSERT INTO Departments (department_id,department_name) VALUES (27,'Pachis � la Croix');
INSERT INTO Departments (department_id,department_name) VALUES (28,'Rue de la Vall�e');
INSERT INTO Departments (department_id,department_name) VALUES (29,'Ruelle Nassau');
INSERT INTO Departments (department_id,department_name) VALUES (30,'Rue de Courtrai');
INSERT INTO Departments (department_id,department_name) VALUES (31,'Rue Fleurie');
INSERT INTO Departments (department_id,department_name) VALUES (32,'Chemin du Bois');
INSERT INTO Departments (department_id,department_name) VALUES (33,'Rue Brou des Saules');
INSERT INTO Departments (department_id,department_name) VALUES (34,'Rue des Nations-Unies');
INSERT INTO Departments (department_id,department_name) VALUES (35,'Pachis du Capitaine');
INSERT INTO Departments (department_id,department_name) VALUES (36,'Rue Fonds de nos Bois');
INSERT INTO Departments (department_id,department_name) VALUES (37,'Rue Buraufosse');
INSERT INTO Departments (department_id,department_name) VALUES (38,'chemin des Hortensias');
INSERT INTO Departments (department_id,department_name) VALUES (39,'Rue Nicolas Gaumet');
INSERT INTO Departments (department_id,department_name) VALUES (40,'Rue Tige-de-Hogne');
INSERT INTO Departments (department_id,department_name) VALUES (41,'Rue du Tige');
INSERT INTO Departments (department_id,department_name) VALUES (42,'Rue de la Fontaine');
INSERT INTO Departments (department_id,department_name) VALUES (43,'Malmy');
INSERT INTO Departments (department_id,department_name) VALUES (44,'Rue Henri Tholom�');
INSERT INTO Departments (department_id,department_name) VALUES (45,'Avenue du Tendeur');
INSERT INTO Departments (department_id,department_name) VALUES (46,'Place du Perron');
INSERT INTO Departments (department_id,department_name) VALUES (47,'Grenzstra�e');
INSERT INTO Departments (department_id,department_name) VALUES (48,'Rue des Artisans');
INSERT INTO Departments (department_id,department_name) VALUES (49,'Place du Vin�ve');
INSERT INTO Departments (department_id,department_name) VALUES (50,'Rue de la Providence (GS)');
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (1,'Slovaquie',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (2,'Madagascar',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (3,'Pérou',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (4,'Malawi',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (5,'Îles Caïmans',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (6,'Irlande',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (7,'Russie',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (8,'Territoires palestiniens',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (9,'Timor oriental',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (10,'Guinée-Équatoriale',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (11,'Mauritanie',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (12,'Aruba',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (13,'Turkménistan',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (14,'Thaïlande',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (15,'Géorgie',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (16,'Indonésie',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (17,'Québec',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (18,'Soudan du Sud',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (19,'Guatemala',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (20,'Taïwan',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (21,'Samoa',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (22,'Côte dIvoire',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (23,'Saint-Vincent-et-les-Grenadines',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (24,'Nigéria',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (25,'Uganda',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (26,'Sierra Leone',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (27,'Etats-Unis',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (28,'Pays-Bas',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (29,'Suisse',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (30,'Lituanie',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (31,'Île de Man',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (32,'Roumanie',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (33,'Guinée-Équatoriale',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (34,'Liberia',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (35,'Rwanda',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (36,'Timor oriental',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (37,'Niger',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (38,'Îles Mariannes du Nord',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (39,'Nicaragua',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (40,'Tchad',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (41,'Kazakhstan',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (42,'Belgique',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (43,'Îles Mariannes du Nord',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (44,'Angola',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (45,'Israël',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (46,'Turkménistan',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (47,'Lesotho',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (48,'',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (49,'Malte',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO Projects (project_id,project_name,start_date,end_date) VALUES (50,'Danemark',NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY,NOW() - INTERVAL FLOOR(1 + (RAND() * 10000)) DAY);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (1,38);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (2,37);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (3,18);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (4,9);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (5,2);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (6,35);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (7,13);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (8,22);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (9,17);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (10,19);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (11,49);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (12,39);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (13,24);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (14,45);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (15,39);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (16,32);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (17,19);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (18,37);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (19,36);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (20,14);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (21,35);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (22,6);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (23,10);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (24,31);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (25,33);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (26,35);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (27,44);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (28,45);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (29,23);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (30,26);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (31,29);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (32,32);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (33,40);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (34,45);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (35,21);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (36,13);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (37,4);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (38,5);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (39,34);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (40,8);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (41,9);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (42,27);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (43,42);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (44,31);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (45,37);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (46,45);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (47,50);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (48,46);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (49,44);
INSERT INTO EmployeeProjects (employee_id,project_id) VALUES (50,24);
